# Generated by Django 3.0.7 on 2020-06-12 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=20)),
                ('des', models.TextField()),
                ('audio', models.FileField(upload_to='audio/')),
                ('sub', models.CharField(choices=[('yearly', 'YEARLY'), ('monthly', 'MONTHLY')], default='MONTHLY', max_length=10)),
                ('cg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Category')),
            ],
        ),
    ]
